In [1]:
#Julian Adames-Ng
#DATA 602 - Advanced Programming Techniques
#Prof. Schettini
#Fall 2023

#1. What are the similarities and differences between pandas and numpy?   Include some type of example with code.

#Both tools are used to deal with numerical data.  PanDas are
#actually built from Numpy, but Numpy is mainly used to work
#on modeling and scientific work which involves numerical data
#and PanDas are for manipulation of data frames and data analysis.

#2. What is the ndarray in numPy?

#ndarray stands for N-Dimensional array.  Arrays can be used to represent vectors,
#and matrices.  They can also be used to perform element wise operations as well
#as linear operations such as matrix multiplication.

#3. Create a 1D array of numbers from 0 to 9

#Desired Output:

#array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np
list1 = [0,1,2,3,4,5,6,7,8,9]
array1 = np.array(list1)

print(array1, type(array1))

#4. Extract all odd numbers from array1

array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
list1 = array1.tolist()

for i in list1:
  if i%2 != 0:
    list1.pop(list1.index(i))

array1 = np.array(list1)

print(array1, type(array1))

#5. Get the common items between a and b

#input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Desired Output:

#array([2, 4])

a = a.tolist()
b = b.tolist()
c = []

for i in a:
  for j in b:
    if j == a[a.index(i)] and i not in c:
      c.append(i)

c = np.array(c)

print(c, type(c))



#6. From array a remove all items present in array b

#Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

#Desired Output:

#array([1,2,3,4])

a = a.tolist()
b = b.tolist()

for i in a:
  for j in b:
    if j == i:
      a.pop(a.index(i))

a = np.array(a)
print(a, type(a))


#7. Find out if iris has any missing values.



# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

import pandas as pd

iris = pd.DataFrame(iris)

iris

#When comparing the created dataframe, iris, to the full text shown in the url,
#all of the numerical data is retrieved.  If I'm not mistaken, the "dtype"
#declaration specifies to retrieve only floating point values.  The full text shows
#an additional column with either "Iris-setosa" or "Iris-versicolor" strings as data values.

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0 2 4 6 8] <class 'numpy.ndarray'>
[2 4] <class 'numpy.ndarray'>
[1 2 3 4] <class 'numpy.ndarray'>


0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]